google-ID: ''

menu:
- {name: 'About', url: 'about'}
- {name: 'Academics', url: 'academics'}
- {name: 'Experience', url: 'experience'}
- {name: 'Leadership', url: 'leadership'}
- {name: 'Projects', url: 'projects'}
- {name: 'Learning', url: 'learning'}
- {name: 'Recommendations', url: 'recommendations'}
- {name: 'Contact', url: 'contact'}

social:
- {icon: 'file-text-o', link: '/assets/pdf/FMS_Samarth_Gupta.pdf'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/samarth-gupta-b932031b4'}
- {icon: 'github', link: 'https://github.com/sgupta2501'}
